baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "FireSquid's Portfolio"
theme = 'showfolio'


[params]
  name = "FireSquid's Portfolio"
  description = "Jonathan Deiss's portfolio for game development."
  author = "Jonathan Deiss"
  authorEmail = "jonathan@firesquid.co"
  authorImage = "/images/firesquid_nobg.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - John Doe · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey, I'm Jonathan Deiss (a.k.a. FireSquid)"
  tagline = "Game Developer and Designer"
  description = "I like making games and solving problems."
  contact = "https://twitter.com/"

[params.homepage.social]
  github = "https://github.com/FireSquid6"

[params.homepage.resume]
  gamedev_skills = ["Programming in Godot", "Programming in Unity", "Programming in Gamemaker Studio 2", "Game Mechanics Design", "Game Systems Design", "Game Level Design"]

[[params.homepage.resume.work]]
  name = "Hobbiest Programmer"
  role = ""
  duration = "Always"

[[params.homepage.resume.work]]
  name = "Real Ocelot Studios"
  role = "Lead Game Developer"
  duration = "August 2022 - Present"

[[params.homepage.resume.work]]
  name = "Ginga Games"
  role = "Game Developer & Level Designer"
  duration = "January 2022 - May 2022"