baseURL = "/"
languageCode = "en-us"
title = "Firesquid's Portfolio"
theme = "firesquid-portfolio"

[params]
    email = "mailto:jdeiss06@gmail.com"
    discord = "https://discord.gg/HCqHcRWRZE"
    linkedin = "https://www.linkedin.com/in/jonathan-deiss-716008248/"


[[params.projects]]
    github = "https://github.com/FireSquid6/tsp-heuristic-solutions"
    thumbnail = "/images/tsp.png"

    title = "Traveling Salesman Problem Heuristic Solutions Analysis"
    description = "A project where I analyze various heuristic solutions to the traveling salesman problem and gather data on both time and space complexity. Made for my city's science fair."
    date = "2022-2023"

[[params.projects]]
    github = "https://github.com/firesquid6/portfolio-site"
    title = "This website"
    thumbnail = "/images/firesquid_nobg.png"
    description = "Built with a custom hugo theme. My first 'real' project."
    date = "1-2-2022"

[[params.projects]]
    github = "https://github.com/FireSquid6/dodge-roll"
    itch = "https://firesquid4004.itch.io/dodge-roll"

    thumbnail = "/images/dodge-roll.png"
    title = "Dodge Roll"
    description = "A game I made in just 48 hours for the GMTK game jam 2022 with the theme of 'Roll of the Dice.'"
    date = "7-15-2022"


[[params.projects]]
    github = "https://github.com/firesquid6/teleorb"
    itch = "https://firesquid4004.itch.io/teleorb-classic"
    site = "https://teleorb.firesquid.co"

    thumbnail = "/images/input_hint.png"
    title = "Teleorb"
    description = "A 2d platformer made using Godot 4. I originally developed it in Gamemaker when I was 15, but am now remaking it in my free time."
    date = "11-20-2022"


[[params.projects]]
    github = "https://github.com/FireSquid6/Poltergeist-Heist"
    itch = "https://firesquid4004.itch.io/poltergeist-heist"

    thumbnail = "/images/poltergeist_heist.png"
    title = "Poltergeist Heist"
    description = "A puzzle platformer I made in Godot 3 for the Godot Wild Jam #43 in one week. It scored an overall ranking of 15 out of 60."
    date = "3-11-2022"

[[params.resume.skills]]
    skill = "Web building with the MERN stack"

[[params.resume.skills]]
    skill = "Static website creation using Hugo"

[[params.resume.skills]]
    skill = "Scripting with javascript or python"

[[params.resume.skills]]
    skill = "Building CLI's with python's Typer"

[[params.resume.skills]]
    skill = "Game Development using Godot 3 and 4"

[[params.resume.skills]]
    skill = "Game Development using Gamemaker Studio 2"

[[params.resume.education]]
    title = "MITxPro"
    description = "An online bootcamp offered by MIT. It teaches fullstack development."
    date = "2022 - 2023"
    type = "Bootcamp"

link = "https://xpro.mit.edu/programs/program-v1:xPRO+PCCx+R1/"

[[params.resume.education]]
    title = "Veritas Academy"
    description = "A classically modeled private school in Austin, Texas."
    type = "High School"
    date = "2020 - 2024"


[[params.resume.experience]]
    title = "Ginga Games"
    description = "A now terminated HTML5 game studio. I worked with them for a brief period in early 2022 as a level designer before the discord server was deleted and I lost contact with all team members. The domain their website was on now seems to be used by a minecraft server."
    type = "Small Group"
    date = "2022"

[[params.resume.reading]]
    title = "Clean Code"
    description = "A book on how professional software engineers write code that is easy to read and maintain."
    author = "Robert C. Martin"
    link = "https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882"
    date = "Published 2008, Read 2023"


[[params.resume.reading]]
    title = "The Pragmatic Programmer, 20th Anniversary Edition"
    description = "A book written by two experienced software engineers primarily on how to write code that helps your team and your future self."
    author = "David Thomas, Andrew Hunt"
    link = "https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/"
    date = "Published 2019, Read 2022"

[[params.resume.reading]]
    title = "14 Habits of Highly Productive Developers"
    author = "Zeno Rocha"
    description = "A book featuring many interviews with many prominent software engineers about various habits that allowed them to succeed."
    date = "Published 2020, Read 2022"
    link = "https://14habits.com/"