baseURL = "/"
languageCode = "en-us"
title = "Firesquid's Portfolio"
theme = "firesquid-portfolio"

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/boostrap.bundle.min.js"
    target = "assets/js/bootstrap"